# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OO87vsoHO6t6NnbMYrvXht2wfmHuMavy
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -qr requirements.txt

import torch
import utils
display = utils.notebook_init()

from utils.downloads import attempt_download

p5 = ['n', 's', 'm', 'l', 'x']  # P5 models
cls = [f'{x}-cls' for x in p5]  # classification models

for x in cls:
    attempt_download(f'weights/yolov5{x}.pt')

# Commented out IPython magic to ensure Python compatibility.
import os
os.makedirs("../datasets/", exist_ok=True)
# %cd ../datasets/

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Rig4Wm7yMAhBIHmqxQIR")
project = rf.workspace("supermarketproductdetection").project("product_classification-b0ygy")
version = project.version(2)
dataset = version.download("folder")

dataset_name = dataset.location.split(os.sep)[-1]
os.environ["DATASET_NAME"] = dataset_name

# Commented out IPython magic to ensure Python compatibility.
# %cd ../yolov5
!python classify/train.py --model yolov5s-cls.pt --data $DATASET_NAME --epochs 100 --img 128 --pretrained weights/yolov5s-cls.pt

